FROM node:12

WORKDIR /usr/src/app/portal_legais_regulatorios_front

COPY package*.json ./

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

EXPOSE 4201

CMD ["npm", "start"]